### PR TITLE
Refactor with interfaces for DB and Zulip interaction

### PR DESCRIPTION
**Pull request by parsn1psoup**
Interfaces will allow us to mock the DB and Zulip interaction, and have more unit tests.
This PR does the following:

* Split up code into several files
* Add interfaces ´RecurserDB´ for DB lookups of subscriber information, and ´APIAuthDB´ for DB lookups of API/authentication tokens. Move existing implementation of DB queries into ´FirestoreRecurserDB´ and ´FirestoreAPIAuthDB´ types implementing these interfaces.
* Add interfaces ´userRequest´ for handling user requests to the bot through the client (atm Zulip), and ´userNotification´ for sending notifications to users (e.g for matches and offboarding). Move existing implementation of client interaction into ´zulipUserRequest´ and ´zulipUserNotification´ types implementing these interfaces.
* Add ´PairingLogic´ type that holds the types for DB and client interaction.
* Make the HTTP handle functions methods with ´PairingLogic´ as the receiver.

To do:
* ´context´ was added, but not used in a meaningful way yet. It shouldn't do any harm but maybe some ´context.Background()´ can be cleaned up even before merging this.
* Error handling might not be super consistent yet (when to log? when to panic?), but can be addressed separately I guess.

This PR is pretty big and I'm not sure if it's reviewable or testable enough to be merged as is. Even if we don't end up merging it, it has been useful as a learning project and can maybe serve as a reference for future discussions.

Thanks @rickypai, @nyghtowl, @Mathew-Estafanous and @ameliariely for advice and pairing sessions on this!

### CODE REVIEW

**Comment by thwidge** [comment]
This is such a great contribution to pairing bot and i'm stoked to do whatever's necessary to get all these changes into production! @parsn1psoup and I are chatting out-of-band, and it sounds like we're gonna work on merging (and thus going to production) sometime this week.

Seconding @parsn1psoup -- huge thanks to all of you @rickypai @nyghtowl @Mathew-Estafanous @ameliariely 🙏

**Comment by Mathew-Estafanous** [comment]
Sounds great! If you are ok with it, could I join you guys as you work on getting this update on to production?

**Comment by thwidge** [comment]
@Mathew-Estafanous Yes absolutely! I'll start a group chat on zulip

**Review by rickypai — COMMENTED** [review]
comments on context. although some comments are outdated based on the latest commit

**Comment by parsn1psoup** [comment]
Thank you for the comments @rickypai ! Should be resolved now.

**Pull request merged**
